### ISSUE TITLE
Does this model use 538's elo dataset as input data?

### ISSUE THREAD

**Issue by jonathanelbailey** [banamwana/NFLGamePredictor#1]
Hi there.  I came across your repository looking for examples of how to generate QB values, and this project seems promising.  It looks like this is a personal project, and there's missing details about what dataset the project codebase is expecting to work with.  Is it the original 538 dataset?

**Comment by banamwana** [comment]
Hi Jonathan,
This was a hobby project. It downloaded game and player stats from
footballreference.com when access was still free. Last I checked, you have
to pay for access to these stats now.

The qb value was designed to allow a user to make up their own passer
rating, given the commonly used ones seem arbitrary.

Thanks,
G
